name: tarot_ai
publish_to: none
version: 0.1.6+15

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.1.5
  firebase_app_check: ^0.3.1+7
  firebase_messaging: ^15.2.10
  firebase_remote_config: ^5.4.7
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_local_notifications: ^21.0.0
  google_mobile_ads: ^5.3.1
  app_tracking_transparency: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  timezone: ^0.11.0
  camera: ^0.12.0+1
  google_mlkit_image_labeling: ^0.14.2
  flutter_image_compress: ^2.4.0
  get_it: ^9.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1
  image: ^4.8.0
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  in_app_purchase: ^3.2.3
  url_launcher: ^6.3.1
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/Tarot_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/onboarding/
    - assets/translations/
    - images/
    - assets/card-images/
    - assets/card-images/wands/
    - assets/card-images/cups/
    - assets/card-images/swords/
    - assets/card-images/pentacles/
